Update dependencies

diff --git a/.github/workflows/firebase-hosting-pull-request-main.yml b/.github/workflows/firebase-hosting-pull-request-main.yml
--- a/.github/workflows/firebase-hosting-pull-request-main.yml
+++ b/.github/workflows/firebase-hosting-pull-request-main.yml
@@ -13,6 +13,12 @@ jobs:
     if: github.event.pull_request.merged == true
     runs-on: ubuntu-latest
     steps:
+      - run: |
+          if [[ "${{ github.event.pull_request.base.ref }}" != "main" || "${{ github.event.pull_request.head.ref }}" != "develop" ]]; then
+            echo "Error: Pull requests to main should be from the develop branch only."
+            exit 1
+          fi
+
       - uses: actions/checkout@v4
           
       - uses: subosito/flutter-action@v2
